shapes:
	gcc -c shapes.c
	gcc shapes.o -o shapes
clean:
	rm shapes shapes.o cstrptr cstrptr.o cstr.o cstr bitwise.o funbitwise.o bitwise 
cstrptr:                                                                    
	gcc -c cstrptr.c
	gcc cstrptr.o -o cstrptr
cstr:
	gcc -c cstr.c
	gcc cstr.o -o cstr

bitwise:
	gcc -c bitwise.c funbitwise.c
	gcc bitwise.o funbitwise.o -o bitwise
