shape:
	gcc -c shapes.c 
	gcc shapes.o -o shapes

cstrptr:
	gcc -c cstrptr.c
	gcc cstrptr.o -o cstrptr

cstr: 
	gcc -c cstr.c 
	gcc cstr.o -o cstr

bitwise:
	gcc -c macro.c bitwise.c
	gcc macro.o bitwise.o -o bitwise


cl_shapes:
	rm shapes.o shapes


cl_cspt:
	rm cstrptr.o cstrptr


cl_cstr:
	rm cstr.o cstr


cl_bitwise:
	rm macro.o bitwise.o bitwise

